name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main  # Sempre que der push na main, faz deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm install --legacy-peer-deps

      - name: Build do projeto
        run: CI=false npm run build

      - name: Faz deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
